language: c

before_install:
  - sudo apt-get update -qq
  - pip install codecov

install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

script:
  - export FILE_NAME=AVR-NETINO-$TRAVIS_BRANCH-All-HEX.zip
  - echo $FILE_NAME
  - cd ./hardware/avrnetio/bootloaders/optiboot/
  - make -f ../atmega/Makefile anio
  - make -f ../atmega/Makefile diecimila duemilanove
  - zip $FILE_NAME *.hex

after_success:
  - codecov

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: 
    - $FILE_NAME
  on:
    tags: true

notifications:
  email:
    - c-n-i@web.de

env:
  global:
    secure: ZlAl/3jW58m4aGJhuBWPAz9O2OdYfKoiaUL+2Ltu+CXxEYc7dDkrZw7LuB9SqhkhkJOUS5CUGr7otJTNGbuwEEEmuD2p8TAyDKoutYNPFL7XgbuMEuslwl1u7X5OdYyTXu+zgYmpHF6zdSabZ8fBvyshA3OgBRVxTarYXPyozPCVUAM7DoqoQugZw8ksGtDG0hhHbbHOkFAOuTKMtz8MUj45QdQtYVb3SWg0btgOJ79xBNg2TLA9s/h7392Wyj6RoDrkmJxw/X40LGsBqBUc/GvkRpgumETK/N9RO0FfHVuLmdv0NKhK+9+8i0jiANoZ//08/urmWZ+2ulil1W2lF8Zc0OAiyYYcDcJHmwvmLB4939XE7Uuo/2IZuHutQukyVvTAKc6r2+BD6xPrxyJVz67QsVJxkPBif1PMWfJqsVEcSzeardVOGOqN67wdcTRcDh9b2DwLzOq5HwNjvjqDk7ePbF1I/b/Qg/Gj7hN9xjdlXW4XqRGM2lC5hMoVMG5zpQpoFv64nOAA4QFALXEzjX9gk0oUe74eGqvt+xhsRy2kiMxZruV9rhVks0FFVkec0ClL0AmD82dmSfTzUnJUNWml7zhwvz9nnpk1Wkwn9OLV+m5lnoMJkxkvQj9lK9horODzpQxnr0Pl3/uqkdA5EPhUMhzS39v42S3taAtKWU8=
